# Profile: navet
rerun-incomplete: True
printshellcmds: True
benchmark-extended: True
keep-going: True

# RESOURCES
executor: slurm
jobs: 300
retries: 3
default-resources:
  slurm_account: dev_gpu
  slurm_partition: dev_gpu  
  slurm_gres: gpu:1
  runtime: 10
  mem_mb: 900000
  tasks: 1
  cpus_per_task: 1
  # slurm_extra: "'--exclude=node07,node08'"

# REPRODUCIBILITY
use-apptainer: True
singularity-args: "--bind /mnt/beegfs/home/mkoshkin/"

# CONFIG
config:
  MAX_RAM_MB: 900000
  MAX_THREADS: 64
  MAX_VRAM_MB:  95830
  todo: soroban